### ISSUE TITLE
[BUG] Sources list on ubuntu focal

### ISSUE THREAD

**Issue by emidev98** [tuxedocomputers/linux#1]
Dear Tuxedo Team,

I have found that after installing Ubuntu 20.04 on Polaris 15 (v3) the repository for security was miss configured on my sources.list as:
```
deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse
```

After searching on your repos I could find that the right URL is:
```
deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
```

Maybe I am mistaking, but let me know if this is the correct way.

**Comment by Matombo** [comment]
Unrelated to kernel
