### ISSUE TITLE
linux-image-6.8.0-101041-tuxedo keyboard not working after resume from suspend

### ISSUE THREAD

**Issue by fvalasiad** [tuxedocomputers/linux#10]
Hello!

Just wanted to point out that the aforementioned kernel breaks my polaris 15 keyboard after resume from suspend.

The keyboard just doesn't work, funnily enough kde connect's keyboard works though!

External USB plugged keyboards don't work either!

Booting into the older 6.5 kernel fixes this.

Additionally I've noticed that even suspend sometimes fails, only locking KDE. Suspending again usually works correctly though.

I am on default TuxedoOS install.

**Comment by tuxedo-wse** [comment]
please reopen the issue over at https://gitlab.com/tuxedocomputers/development/packages/linux and add whitch generation of polaris you have a problem with
