### ISSUE TITLE
OS not managing space on /boot adequately

### ISSUE THREAD

**Issue by circleape** [tuxedocomputers/linux#7]
Since last week I have been receiving this error in my InfinityBook Pro 14 Gen6 with Ubuntu 22.04.03 LTS:

![Screenshot from 2023-09-19 14-30-50](https://github.com/tuxedocomputers/linux/assets/99277051/767710fc-8761-4bf4-a715-72809a5ddb6a)
![Screenshot from 2023-09-19 14-32-15](https://github.com/tuxedocomputers/linux/assets/99277051/4f6378c5-5fb7-4f8c-a240-cc40e040b1fd)

Not sure why the OS is keeping very old kernel and initrd files in there.

That issue is causing the OS to not be able to write new initrd files when updating:

> Setting up initramfs-tools (0.140ubuntu13.4) ...
> update-initramfs: deferring update (trigger activated)
> Processing triggers for initramfs-tools (0.140ubuntu13.4) ...
> update-initramfs: Generating /boot/initrd.img-6.2.0-10022-tuxedo
> I: The initramfs will attempt to resume from /dev/dm-2
> I: (/dev/mapper/system-swap)
> I: Set the RESUME variable to override this.
> zstd: error 25 : Write error : No space left on device (cannot write compressed 
> block) 
> E: mkinitramfs failure zstd -q -1 -T0 25
> update-initramfs: failed for /boot/initrd.img-6.2.0-10022-tuxedo with 1.
> dpkg: error processing package initramfs-tools (--configure):
>  installed initramfs-tools package post-installation script subprocess returned 
> error exit status 1
> Errors were encountered while processing:
>  initramfs-tools
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by circleape** [comment]
The problem still happens

**Comment by Matombo** [comment]
Problem should be fixed by now with a tuxeod-tomte update. Closing
